config/routes.rb
Nonriservato::Application.routes.draw do
  get '' => redirect("/#{I18n.default_locale}")
  scope "(:locale)", locale: /en|it/ do
    devise_for :organizations

    namespace :admin do
      root to: "projects#index"

      # devise_for :organizations, :skip => ['session', 'password']

      resources :posts
      resources :events
      resources :partners, only: [:index]

      resources :projects, except: [:show] do
        get :json_names, on: :collection
      end
      resources :organizations do
         get :json_names, on: :collection
      end
      resources :external_organizations do
         get :json_names, on: :collection
      end

      resources :workshops

      resources :images, only: [:destroy]
      # resources :external_partners, only: [:index]
      match 'external_partners' => "organizations#edit_external_partners"
      match 'update_external_partners' => "organizations#update_external_partners"
    end

    resources :external_partnerships, only: [:index, :show]
    resources :external_organizations, only: [:index, :show]
    resources :posts, only: [:index, :show, :update]
    resources :events, only: [:index, :show, :update]
    resources :projects, only: [:index, :show, :update]
    resources :organizations, only: [:index, :show]
    resources :workshops, only: [:index, :show]
    resources :pages, only: [:new, :update, :create, :edit]

    get '/pages/:slug', to: 'pages#show', as: 'page'

    match 'admin/edit_profile' => 'admin/organizations#edit'

    root to: 'home#index'
  end
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  PAPERCLIP_STORAGE_OPTS = {}

  if Rails.env.production?
    PAPERCLIP_STORAGE_OPTS.merge!(
      storage: :s3,
      s3_credentials: S3_SECRETS,
      path: "/pdf/:id/:style/:filename",
      s3_host_name: 's3-eu-west-1.amazonaws.com',
      default_url: '/assets/missing_:style_image.png'
    )
  end

  attr_accessible :active, :address, :date_begun, :date_ended, :definition, :description, :invisible, :name, :url, :zone, :images_attributes, :pdf_download, :workshop_partner_ids
  # Associations
  has_many :images, as: :imageble, order: 'id ASC'
  has_many :workshop_partnership
  has_many :workshop_partners, through: :workshop_partnership, :source => :organization, :uniq => true
  has_attached_file :pdf_download, PAPERCLIP_STORAGE_OPTS

  # Validations
  validates_presence_of :name, message: 'devi dare un nome al workshop'
  validates_length_of :definition, minimum: 10, maximum: 150, allow_blank: false, message: "la definizione dev'essere presente e meno lunga di 150 caratteri"

  accepts_nested_attributes_for :images, allow_destroy: true

  def image(style='medium')
    if images.empty?
      "/assets/missing_#{style}_project.jpg"
    else
      images[0].data(style)
    end
  end

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
end

app/controllers/admin/workshops_controller.rb
# encoding: utf-8
class Admin::WorkshopsController < ApplicationController
  before_filter :protect_admin
  before_filter :process_params
  before_filter :set_workshop, only: %i[edit update destroy]
  before_filter :set_current_tab, only: %i[new create edit]

  def index
    @workshops = Workshop.all
  end

  def new
    @workshop = Workshop.new
    @workshop.images.build
  end

  def create
    @workshop = Workshop.new(params[:workshop])
    respond_to do |format|
      if @workshop.save
        format.html { redirect_to admin_workshops_path, notice: I18n.t('workshops.workshop_created') }
        format.json { render json: @workshop, status: :created, location: @workshop }
      else
        format.html { render action: 'new' }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @workshop.images.build
    @hash_partners = Organization.retrieve_hash(@workshop.workshop_partners.collect { |o| o.id })
  end


  def update
    if @workshop.update_attributes(params[:workshop])
      flash[:notice] = I18n.t('workshops.workshop_updated')
      redirect_to admin_workshop_path(@workshop)
    else
      flash.now[:alert] = I18n.t('workshops.workshop_not_updated')
      render :edit
    end
  end

  def destroy
    if @workshop.destroy
      flash[:notice] = I18n.t('workshops.workshop_destroyed')
      redirect_to admin_workshops_path
    else
      flash.now[:error] = 'Unable to destroy this workshop'
      render :edit
    end
  end

  private

  def process_params
    if params[:workshop]
      if params[:workshop]['workshop_partner_ids'] == '[]'
        params[:workshop]['workshop_partner_ids'] = []
      else
        params[:workshop]['workshop_partner_ids'] = params[:workshop]['workshop_partner_ids'].split(',')
        @hash_partners = Organization.retrieve_hash(params[:workshop]['workshop_partner_ids'])
      end
    else
       @hash_partners = []
    end
  end

  def set_workshop
    @workshop = Workshop.find(params[:id])
  end

  def set_current_tab
    @current_tab = 'workshops'
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_filter :find_workshop, only: [:show]

  def index
     q = params[:q].blank? ? {"s"=>"date desc"} : params[:q]
     @search = Workshop.search(q)
     @workshops = @search.result.page(params[:page]).per(20)
     @count = @workshops.count
     # @project_categories = ProjectCategory.all
  end

  def show
    @current_tab = "workshops"
    @workshop = Workshop.find(params[:id])

    # @partners = @project.partners
    # @external_partners = @project.external_partners
    #
    # @projects = @project.organization.projects
    # @projects = @projects.reject { |p| p == @project }
        #
        # @events = @project.events

  end

  # def update
  #     @post = Post.find(params[:id])
  #     p_highlighted = params[:post][:highlighted]
  #     p_highlighted = (p_highlighted == "1") ? true : false
  #
  #     if p_highlighted != @post.highlighted?
  #       if p_highlighted
  #         # aggiungo l'highlight
  #         h = Highlight.new
  #         h.weight = params[:post][:weight]
  #         @post.highlight = h
  #         @post.save
  #       else
  #         # tolgo l'highlight
  #         @post.highlight.destroy
  #       end
  #     else @post.highlighted? && (@post.highlight.weight != params[:post][:weight])
  #        @post.highlight.weight = params[:post][:weight]
  #        @post.highlight.save
  #     end
  #
  #     redirect_to post_path(@post)
  #
  # end

  def find_workshop
    @workshop = Workshop.find params[:id]
    # If an old id or a numeric id was used to find the record, then
    # the request path will not match the post_path, and we should do
    # a 301 redirect that uses the current friendly id.
    if request.path != workshop_path(@workshop)
      return redirect_to @workshop, :status => :moved_permanently
    end
  end

end

app/views/workshops/_workshop.html.erb
<% array_of_colors = ["color_1", "color_2", "color_3", "color_4", "color_5", "color_6"] %>
<% @workshops.each_slice(2) do |row| %>
   <% row.each_with_index do |w, i| %>
      <% color = "color_3" %>
      <div class="grid_6 <%= i == 0 ? "alpha" : "omega" %>">
      <%= link_to (admin_namespace? ? edit_admin_workshop_path(w) : workshop_path(w)), :class => "workshop_element #{"last" if i == 1} #{color}" do %>
         <%= image_tag w.image("medium"), :title => "#{w.name}" %>
         <!-- <div class="year"><%# w.date_begun.year unless w.date_begun.nil? %></div> -->
         <div class="title"><%= w.name unless w.nil? %></div>

         <p class="description"><%= w.definition unless w.nil? %></p>
      <% end %>
      </div>
   <% end %>
<% end %>

app/views/workshops/index.html.erb
<div class="grid_12">
  <div class="banner_projects">
     <%= image_tag "banner_progetti.jpg", :title => "workshop" %>
    <div>laboratori creativi</div>
  </div>

  <div class="intro">
    <%= t('.intro_text_html') %>
  </div>
</div>

<% if params[:locale] == 'en' %>
  <div class="grid_12">
    <div class="intro">
      <p>
        <%= link_to 'Discover our workshops', workshops_path(locale: :it)%> (This page is only available in Italian)
      </p>
    </div>
  </div>
<% else %>
  <div class="grid_12">
    <div class="sort_bar">
      <span>Ordina per:</span>
      <%= sort_link @search, :date, "Data", default_order: :desc %> //
      <%= sort_link @search, :name, "Nome" %> //
    </div>
    <%= render "workshops/workshop" %>
  </div>
  <div class="grid_12 pagination">
    <%= paginate @workshops %>
  </div>
<% end %>

app/views/workshops/show.html.erb
<% set_meta_tags(
  title: @workshop.name,
  description:  @workshop.definition,
  og: {
  image: image_path(@workshop.images[0].data(:big))
  })
%>

<div class="grid_12">
   <div class="clearfix heading">
      <h1><%= @workshop.name %></h1>
      <div class="date"><%= l(@workshop.date_begun, :format => :long) %> <%= (@workshop.date_ended.blank? || @workshop.date_ended > Date.today) ? "> Oggi (Attivo)" : ("> " + l(@workshop.date_ended, :format => :long) + " (archiviato)") %></div>
   </div>
   <div class="grid_9 alpha">
      <div class="shared_definition"><%= @workshop.definition %></div>
   </div>
</div>

<div class="grid_9">
   <%# image_tag @workshop.image(:big) %>
   
   <div class="slider-container">
      <ul id="slider">
      	<% @workshop.images.each do |i| %>
      	<li><%= image_tag(i.data(:big)) %></li>
      	<% end %>
      </ul>
   </div>
   
   <div class="shared_description">
      <%= markdown_d @workshop.description %>
   </div>
</div>

<div class="grid_3 sidebar">
   <%= link_to "modifica workshop", edit_admin_workshop_path(@workshop), :class => "edit_object" if admin? %>
   
   <% if @workshop.url.size > 0 %>
   <p>
      <strong>web</strong>: <%= link_to @workshop.url.split("//").last, ensure_url(@workshop.url), :target => "_blank" %>
   </p>
   <% end %>
   
   <% if false %>
   un progetto <span>di</span><br>
   <%= link_to organization_path(@workshop.organization) do %>
      <%= @workshop.organization.name %>
      <div class="square_logo o_image">
         <%= image_tag @workshop.organization.logo(:big_thumb) %>
      </div>
   <% end %>
   <% end %>
   
   <%# render "shared/partners" %>
   
</div>