config/routes.rb
Nonriservato::Application.routes.draw do
  get '' => redirect("/#{I18n.default_locale}")
  scope "(:locale)", locale: /en|it/ do
    devise_for :organizations

    namespace :admin do
      root to: "projects#index"

      # devise_for :organizations, :skip => ['session', 'password']

      resources :posts
      resources :events
      resources :partners, only: [:index]

      resources :projects, except: [:show] do
        get :json_names, on: :collection
      end
      resources :organizations do
         get :json_names, on: :collection
      end
      resources :external_organizations do
         get :json_names, on: :collection
      end

      resources :workshops

      resources :images, only: [:destroy]
      # resources :external_partners, only: [:index]
      match 'external_partners' => "organizations#edit_external_partners"
      match 'update_external_partners' => "organizations#update_external_partners"
    end

    resources :external_partnerships, only: [:index, :show]
    resources :external_organizations, only: [:index, :show]
    resources :posts, only: [:index, :show, :update]
    resources :events, only: [:index, :show, :update]
    resources :projects, only: [:index, :show, :update]
    resources :organizations, only: [:index, :show]
    resources :workshops, only: [:index, :show]
    resources :pages, only: [:new, :update, :create, :edit]

    get '/pages/:slug', to: 'pages#show', as: 'page'

    match 'admin/edit_profile' => 'admin/organizations#edit'

    root to: 'home#index'
  end
end

app/controllers/home_controller.rb
#encoding: utf-8
class HomeController < ApplicationController
  def index
    @events = Event.upcoming.order("date_begun").limit(4)
    @posts = Post.order("date_published DESC").limit(2)

    # @projects = Project.order("RANDOM()").limit(6)
    @highlights = Highlight.order("weight")


    # set_meta_tags title: 'Homepage',
    #               description: 'Non Riservato è la piattaforma online per la riconquista creativa degli spazi pubblici di Milano. Coltiva, corri, scopri, gioca, assaggia: fai da te una città a misura di tutti!',
    #               og: {
    #                 title:            'Homepage',
    #                 description:      'Non Riservato è la piattaforma online per la riconquista creativa degli spazi pubblici di Milano. Coltiva, corri, scopri, gioca, assaggia: fai da te una città a misura di tutti!',
    #                 url:              request.original_url,
    #                 image:            "http://nonriservato.net/assets/header_calendario.jpg"
    #               },
    #               fb:{
    #                 app_id:          '673640696130600'
    #               }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
	<div class="container_12" id="footer">
	   <div class="grid_12 dotted_line"></div>

     <div class="grid_4 about">
        <h4>info</h4>
        <p>Associazione Promozione Sociale<br>
        <strong>Non Riservato</strong><br>
        Via Marsala 8, 20121 Milano<br>
        C.F. 97707020158<br>
        <a href="mailto:info@nonriservato.net">info@nonriservato.net</a></p>

     </div>

     <div class="grid_4 map">
        <h4><%= t('.support_us') %>!</h4>
        <p> <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
	 <input type="hidden" name="cmd" value="_s-xclick">
	 <input type="hidden" name="hosted_button_id" value="KWK5DQHAA83UQ">
	 <input type="image" src="https://www.paypalobjects.com/it_IT/IT/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal è il metodo rapido e sicuro per pagare e farsi pagare online.">
	 <img alt="" border="0" src="https://www.paypalobjects.com/it_IT/i/scr/pixel.gif" width="1" height="1">
	 </form>
	 oppure inviaci un bonifico con la causale "erogazione liberale" a queste coordinate:
	 IBAN: IT 73 E033 5901 6001 0000 0133 194 BIC: BCITITMX C/O: Banca Prossima intestato a: APS NON RISERVATO
        </p>
     </div>



      <!-- <div class="grid_4 map">
         <div class="clearfix">
            <h4>mappa del sito</h4>
         </div>
         <ul>
            <li><a href="/">home</a></li>
            <li><a href="/events">eventi</a></li>
            <li><a href="/projects">progetti</a></li>
            <li><a href="/organizations">organizzazioni</a></li>
            <li><a href="/posts">blog</a></li>
         </ul>
      </div> -->


      <!-- <div class="grid_4 social omega">
         <h4>social</h4>
         <ul>
            <li><a href="http://eepurl.com/zXnZ5">newsletter</a></li>
            <li><a href="http://www.facebook.com/pages/NON-Riservato/438274402925876" target="_blank">facebook</a></li>
         </ul>
      </div> -->

      <div class="grid_4 donations">
         <!-- <div class="clearfix">
            <h4>Con il contributo di:</h4>
         </div> -->

         <%= link_to(image_tag("logo_cariplo.jpg", :class => "cariplo"), "http://www.fondazionecariplo.it") %>
         <%= link_to(image_tag("logo_comune_milano2.jpg", :class => "comune"), "https://www.comune.milano.it") %>
      </div>


      <div class="grid_12 bottom">
         <%= image_tag "logo_icon.png", title: 'logo' %>
         <span><%= "#{t('website').upcase} - #{t('.footer_slogan')}" %></span><br>
         <span class="credits">
					 Credits: brand identity by <%= link_to "Edizioni Perpetua", "http://www.edizioniperpetua.it" %>, web-design and development by <%= link_to "Focus Innovazione Sociale", "http://www.focuscoop.it" %>
				 </span>
      </div>
	</div>
	<%= yield :scripts %>

app/views/home/_header.html.erb
<div class="grid_12" id="header">
	<div id="login_tab" class="<%= "big" if current_organization %>">
	   <% if current_organization %>
	      <p>
					<%= "#{t('hello')} #{current_organization.name}" %><br>
					<%= link_to t('.go_to_admin_area'), admin_root_path %><br>
					<%= link_to t('.exit'), destroy_organization_session_path, method: :delete, class: 'red' %>
	      </p>
	      <div class="square_logo micro">
	        <%= image_tag current_organization.logo(:micro) %>
	      </div>

	   <% else  %>
		 	<%= link_to t('.enter'), new_organization_session_path %>
	   <% end %>

	</div>

	<div id="logo_search_container" class="clearfix">
		<%= link_to (image_tag 'logo.png', title: 'Non Riservato', id: 'logo'), root_path %>
		<%# link_to (image_tag "banner_gallab.png", :title => "Sostieni il Gallab", :id => "banner_gallab"), "https://www.eppela.com/it/projects/9112-realizziamo-il-gallab-non-riservato?t=contributors" %>
		<%= image_tag "5-nr.png", class: 'x1000' %>

	   <form action="<%# search_url %>" id="search_nr">
	       <input type="hidden" name="cx" value="001621681078880853769:bs9kq8zsatc" />
	       <input type="hidden" name="cof" value="FORID:9" />
	       <input type="hidden" name="ie" value="UTF-8" />
	       <%= text_field :qasd, nil, placeholder: "cerca nel sito", id: 'q', name: 'q' %>
	       <input type="image" src="/assets/freccia_search.png" name="sa" id="search_button" />
	   </form>

		<div class="social_icons">
		  <%= link_to (image_tag "social_icons/facebook.png", :title => "Facebook"), "https://www.facebook.com/pages/NON-Riservato/438274402925876?fref=ts", target: "_blank" %>
		  <%= link_to (image_tag "social_icons/instagram.png", :title => "Instagram"), "https://instagram.com/nonriservato/", target: "_blank" %>
		  <%= link_to (image_tag "social_icons/twitter.png", :title => "Twitter"), "https://twitter.com/nonriservato", target: "_blank" %>
		  <%# link_to (image_tag "social_icons/pinterest.png", :title => "Pinterest"), "https://www.pinterest.com/nonriservato/", :target => "_blank" %>
		  <%# link_to (image_tag "social_icons/youtube.png", :title => "Youtube"), "#", :target => "_blank" %>
		  <%= link_to (image_tag "social_icons/newsletter.png", :title => "Newsletter"), "http://eepurl.com/bo2dmv", target: "_blank" %>
		</div>
	</div>

	<%= yield :header_banner %>
</div>

<div class="grid_12">
	<%= render 'shared/language_selector' %>
</div>

<div class="grid_12">
	<div id='cssmenu'>
    <ul class="nav">
       <li><%= link_to('Home', root_path, class: is_active?("home")) %></li>
       <li class='has-sub'><a href='#'><span>About</span></a>
          <ul>
						 <li><%= link_to t('.what_we_are'), page_path('who_we_are') %></li>
             <li><%= link_to t('.who_we_are'), page_path('chi-siamo') %></li>
             <li><%= link_to t('.manifesto'), page_path('manifesto') %></li>
             <li><%= link_to t('.thanks'), page_path('thanks') %></li>
						 <li><%= link_to t('.head_office'), page_path('sede') %></li>
             <li><%= link_to t('.contacts'), page_path('contacts') %></li>
          </ul>
       </li>
       <li><%= link_to t('.calendar'), events_path, class: is_active?("events") %></li>
       <li class='has-sub'>
				 <%= link_to(t('.projects'), projects_path, class: is_active?("projects")) %>
         <ul>
           <li><%= link_to t('.projects'), projects_path, class: is_active?("projects") %></li>
           <li><%= link_to t('.maps'), 'http://maps.nonriservato.net/', target: '_blank' %></li>
         </ul>
       </li>
       <li><%= link_to('Network', organizations_path, class: is_active?("organizations")) %></li>
       <li><%= link_to(t('.support_us'), page_path('support-us')) %></li>
       <li class='has-sub'>
				 <%= link_to(t('.services'), '#') %>
          <ul>
             <li><%= link_to(t('.lectures'), page_path('formazione')) %></li>
             <li><%= link_to(t('.commissioned_projects'), page_path('commissione')) %></li>
             <li><%= link_to(t('.creative_workshops'), workshops_path, class: is_active?("workshops")) %>
             <li><%= link_to('Gallab', page_path('shop')) %></li>
						 <%= link_to t('.sponsor'), page_path('sponsorizza'), class: 'last'%>
          </ul>
       </li>
       <li class='last right'><a href='/posts' class='<%= is_active?("posts") %>'><span>Blog</span></a></li>
    </ul>
   </div>
</div>

app/views/home/index.html.erb
<% if @highlights.empty? %>
  <div class="spacer grid_12">&nbsp; </div>
<% else %>
  <div id="slider" class="grid_12">
     <ul class="bxslider">
     <% @highlights.each do |h| %>
        <%= render :partial => "events/featured_event", :locals => { :event => h.get_parent, :h => h, :hos => @highlights} if (h.highlightable_type == "Event" && !h.get_parent.nil?) %>
        <%= render :partial => "posts/featured_post", :locals => { :post => h.get_parent, :h => h, :hos => @highlights} if (h.highlightable_type == "Post" && !h.get_parent.nil?) %>
        <%= render :partial => "projects/featured_project", :locals => { :project => h.get_parent, :h => h, :hos => @highlights} if (h.highlightable_type == "Project" && !h.get_parent.nil?) %>
        <%= (h.highlightable_type == "Project" && !h.get_parent.nil?) %>
        <%= (h.highlightable_type == "Project") %>
        <%= h.get_parent.nil?  %>
        <%= h.highlightable_type %>
     <% end %>
     </ul>
  </div>
<% end %>

<div class="grid_12 nr_definition">
  <%= t('.intro_text_html') %>
</div>


<!-- <div class="grid_12 nr_definition">
  <%# link_to(image_tag "banner-borderlight.jpg", class: 'banner'), 'https://it.surveymonkey.com/r/borderlight' %>
</div> -->


<div class="grid_12 body">
  <div class="sort_bar">
    <span><%= t('.calendar') %></span>
  </div>
  <% if @events.present? %>
    <%= render "events/event" %>
  <% end %>
</div>

<div class="grid_12 body">
  <div class="sort_bar">
    <span><%= t('.updates') %></span>
  </div>
  <% if @posts.present? %>
    <%= render "posts/post" %>
  <% end %>
</div>