config/routes.rb
Nonriservato::Application.routes.draw do
  get '' => redirect("/#{I18n.default_locale}")
  scope "(:locale)", locale: /en|it/ do
    devise_for :organizations

    namespace :admin do
      root to: "projects#index"

      # devise_for :organizations, :skip => ['session', 'password']

      resources :posts
      resources :events
      resources :partners, only: [:index]

      resources :projects, except: [:show] do
        get :json_names, on: :collection
      end
      resources :organizations do
         get :json_names, on: :collection
      end
      resources :external_organizations do
         get :json_names, on: :collection
      end

      resources :workshops

      resources :images, only: [:destroy]
      # resources :external_partners, only: [:index]
      match 'external_partners' => "organizations#edit_external_partners"
      match 'update_external_partners' => "organizations#update_external_partners"
    end

    resources :external_partnerships, only: [:index, :show]
    resources :external_organizations, only: [:index, :show]
    resources :posts, only: [:index, :show, :update]
    resources :events, only: [:index, :show, :update]
    resources :projects, only: [:index, :show, :update]
    resources :organizations, only: [:index, :show]
    resources :workshops, only: [:index, :show]
    resources :pages, only: [:new, :update, :create, :edit]

    get '/pages/:slug', to: 'pages#show', as: 'page'

    match 'admin/edit_profile' => 'admin/organizations#edit'

    root to: 'home#index'
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :active, :address, :date_begun, :date_ended, :description, :name, :url, :organization_id, :invisible, :zone, :definition, :images, :partners, :external_partners, :partner_ids, :external_partner_ids, :images_attributes, :project_category_id, :project_category

  attr_accessor :weight, :highlighted

  translates :name, :definition, :description

  # Associations
  belongs_to  :organization
  belongs_to  :project_category
  has_one     :highlight, as: :highlightable, dependent: :destroy
  has_many    :images, as: :imageble, order: 'id ASC'
  has_many    :events
  has_many    :partnership
  has_many    :partners, through: :partnership, source: :organization, uniq: true
  has_many    :external_project_partnership
  has_many    :external_partners, through: :external_project_partnership, source: :external_organization

  # Validations
  validates_presence_of :name, message: 'devi dare un nome al tuo progetto'
  validates_presence_of :date_begun, message: 'devi assegnare un inizio al tuo progetto'
  validates_length_of :definition, minimum: 10, maximum: 150, allow_blank: false, message: 'la definizione deve essere presente e meno lunga di 150 caratteri'

  accepts_nested_attributes_for :images, allow_destroy: true

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  def all_organizations
    ao = []
    ao << self.organization
    ao |= self.partners
  end

  def image(style="medium")
    if images.empty?
      "/assets/missing_#{style}_project.jpg"
    else
      images[0].data(style)
    end
  end

  def highlighted?
    !self.highlight.nil?
  end
end

app/controllers/admin/projects_controller.rb
# encoding: utf-8
class Admin::ProjectsController < ApplicationController
  before_filter :authenticate_organization!
  before_filter :process_params
  before_filter :set_project, only: %i[edit update destroy]
  before_filter :set_current_tab, only: %i[new create edit]

  def index
    @projects = admin? ? Project.all : current_organization.projects
  end

  def new
    @project = Project.new
    @project.images.build
  end

  def create
    @project = Project.new(params[:project])
    @project.organization = current_organization

    respond_to do |format|
      if @project.save
        format.html { redirect_to admin_projects_path, notice: I18n.t('projects.project_created') }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @project.images.build

    @hash_partners = Organization.retrieve_hash(@project.partners.collect{|o| o.id})
    @hash_external_partners = ExternalOrganization.retrieve_hash(@project.external_partners.collect{|eo| eo.id})
  end


  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = I18n.t('projects.project_updated')
      redirect_to project_path(@project)
    else
      flash.now[:alert] = I18n.t('projects.project_not_updated')
      render :edit
    end
  end


  def json_names
    @projects = current_organization.projects.where(['UPPER(name) LIKE UPPER(?)', params[:q].to_s + '%']).limit(12)
    @projects.map do |project|
      {
        id: project.id,
        name: project.name
      }
    end

    respond_to do |format|
      format.json { render json: @projects }
    end
  end


  def destroy
    if (current_organization.projects.include?(@project) || admin?)
      if @project.destroy
        flash[:notice] = I18n.t('projects.project_destroyed')
        redirect_to admin_projects_path
      end
    end
  end


  private

  def set_project
    @project = Project.find(params[:id])
  end

  def set_current_tab
    @current_tab = 'projects'
  end

  def process_params
    @hash_partners = []
    @hash_external_partners = []
    if params[:project]
      if params[:project]['partner_ids'] == '[]'
        params[:project]['partner_ids'] = []
      else
        params[:project]['partner_ids'] = params[:project]['partner_ids'].split(',')
        @hash_partners = Organization.retrieve_hash(params[:project]['partner_ids'])
      end

      if params[:project]['external_partner_ids'] == '[]'
        params[:project]['external_partner_ids'] = []
      else
        params[:project]['external_partner_ids'] = params[:project]['external_partner_ids'].split(',')
        @hash_external_partners = ExternalOrganization.retrieve_hash(params[:project]['external_partner_ids'])
      end
    end
    @zone_collection = {
      'tutta la città' => nil,
      'zona 1' => 1,
      'zona 2' => 2,
      'zona 3' => 3,
      'zona 4' => 4,
      'zona 5' => 5,
      'zona 6' => 6,
      'zona 7' => 7,
      'zona 8' => 8,
      'zona 9' => 9
    }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :find_project, only: [:show]

  def index
    
    # q = params[:q].blank? ? {"s"=>"date_begun desc"} : params[:q]
    
     @search = Project.ransack(params[:q])
     @search.sorts = 'date_begun desc' if @search.sorts.empty?
     @projects = @search.result.page(params[:page]).per(20)
     @count = @projects.count
     
     @project_categories = ProjectCategory.all
     
  end
  
  def show
    @current_tab = "projects"
    @project = Project.find(params[:id])
    
    @partners = @project.partners
    @external_partners = @project.external_partners
    
    @projects = @project.organization.projects
    @projects = @projects.reject { |p| p == @project }
    
    @events = @project.events
    
  end
  
  def update
      @project = Project.find(params[:id])
      p_highlighted = params[:project][:highlighted]
      p_highlighted = (p_highlighted == "1") ? true : false
      
      if p_highlighted != @project.highlighted?
        if p_highlighted
          # aggiungo l'highlight
          h = Highlight.new
          h.weight = params[:project][:weight]
          @project.highlight = h
          @project.save
        else
          # tolgo l'highlight
          @project.highlight.destroy
        end
      else @project.highlighted? && (@project.highlight.weight != params[:project][:weight]) 
         @project.highlight.weight = params[:project][:weight]
         @project.highlight.save
      end
      
      redirect_to project_path(@project)
    
  end
  
  
  def find_project
    @project = Project.find params[:id]
    # If an old id or a numeric id was used to find the record, then
    # the request path will not match the post_path, and we should do
    # a 301 redirect that uses the current friendly id.
    if request.path != project_path(@project)
      return redirect_to @project, :status => :moved_permanently
    end
  end    
  

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_featured_project.html.erb
<li>
  <div class="big_featured">
    <div class="grid_9 img_box alpha">
      <%= link_to (image_tag project.image(:featured)), project_path(project) %>
      <div class="title"><%= project.name %></div>
    </div>
    <div class="grid_3 info_box omega">
      <div class="what"><%= t('carousel.what_is_it') %></div>
      <div class="what_details"><%= project.definition %></div>
    </div>
  </div>
</li>

app/views/projects/_project.html.erb
<% array_of_colors = ["color_1", "color_2", "color_3", "color_4", "color_5", "color_6"] %>
<% @projects.each_slice(2) do |row| %>
   <% row.each_with_index do |p, i| %>
      <% color = p.project_category_id == 1 ? "color_1" : "color_2" %>
      <div class="grid_6 <%= i == 0 ? "alpha" : "omega" %>">
      <%= link_to (admin_namespace? ? edit_admin_project_path(p) : project_path(p)), :class => "project_element #{"last" if i == 1} #{color}" do %>
         <%= image_tag p.image("medium"), :title => "#{p.name}" %>
         <div class="title"><%= p.name unless p.nil? %></div>
         <!-- <div class="zone">zona <%= p.zone unless p.nil? %></div> -->
         <!-- <div class="active"><%= p.active ? "attivo" : "archiviato"  %></div> -->

         <p class="description"><%= p.definition unless p.nil? %></p>

         <!-- <div class="who">chi lo fa?</div>
         <div class="who_details"><%= p.organization.name unless p.organization.nil? %></div> -->
      <% end %>
      </div>
   <% end %>
<% end %>

app/views/projects/index.html.erb
<div class="grid_12">
   <div class="banner_projects">
      <%= image_tag "banner_progetti.jpg", :title => "progetti" %>
      <div>progetti non riservati</div>
   </div>
   
   <div class="sort_bar">
      <span>Filtra per tipologia:</span> 
      <% @project_categories.each do |pc| %>
        <%= link_to "#{pc.name}", projects_path(q: {project_category_id_eq: pc.id}) %>
      <% end %>
      <%= link_to "tutti", projects_path(q: {project_category_id_neq: 1}) %>
   </div>

   
   <%= render "projects/project" %>
</div>
<div class="grid_12 pagination">
    <%= paginate @projects %>
</div>

app/views/projects/show.html.erb
<% if @project.images.present? %>
  <% set_meta_tags(
    title: @project.name,
    description: @project.description,
    og: {
      image: image_path(@project.images[0].data(:big))
    }
  ) %>


  <div class="grid_12">
     <div class="clearfix heading">
        <h1><%= @project.name %></h1>
        <div class="date"><%= l(@project.date_begun, :format => :long) %> <%= (@project.date_ended.blank? || @project.date_ended > Time.now) ? "> Oggi (Attivo)" : (l(@project.date_begun, :format => :long) + " (archiviato)") %></div>
     </div>
     <div class="grid_12 alpha">
        <div class="shared_definition"><%= @project.definition %></div>
     </div>
  </div>

  <div class="grid_9">
     <%# image_tag @project.image(:big) %>

     <div class="slider-container">
        <ul id="slider">
        	<% @project.images.each do |i| %>
        	<li><%= image_tag(i.data(:big)) %></li>
        	<% end %>
        </ul>
     </div>


     <div class="shared_description">
        <%= markdown_d @project.description %>
     </div>
  </div>

  <div class="grid_3 sidebar">

    <% if admin? %>
    <div class="admin_box">
       <%= link_to "modifica progetto", edit_admin_project_path(@project), :class => "edit_object" %>

       <%= form_for (@project) do |f| %>

          <%= f.check_box :highlighted, {checked: @project.highlighted?}    %>
          <%= f.label     :highlighted, "Homepage"    %>

          <%= f.label       :weight, "ordine:" %>
  	      <%= f.text_field  :weight, :value => @project.highlight.try("weight"), :style => "width:20px" %>
  	      <br>

          <%= f.submit 'aggiorna' %>

       <% end %>
    </div>
    <% end %>


     <% if @project.url.size > 0 %>
     <p>
        <strong>web</strong>: <%= link_to @project.url.split("//").last, ensure_url(@project.url), :target => "_blank" %>
     </p>
     <% end %>

     <% if false %>
     un progetto <span>di</span><br>
     <%= link_to organization_path(@project.organization) do %>
        <%= @project.organization.name %>
        <div class="square_logo o_image">
           <%= image_tag @project.organization.logo(:big_thumb) %>
        </div>
     <% end %>
     <% end %>


     <%= render "shared/partners" %>

  </div>


  <div class="grid_12">

     <% unless @events.nil? %>
     <div class="sort_bar">
        <span>Eventi di questo progetto:</span>
     </div>
     <%= render "events/event" %>
     <% end %>

     <% if false %>
     <div class="sort_bar red">
        <span>Altri progetti di <%= @project.organization.name %>:</span>
     </div>
     <%= render "projects/project" %>
     <% end %>

  </div>
<% end %>