config/routes.rb
Nonriservato::Application.routes.draw do
  get '' => redirect("/#{I18n.default_locale}")
  scope "(:locale)", locale: /en|it/ do
    devise_for :organizations

    namespace :admin do
      root to: "projects#index"

      # devise_for :organizations, :skip => ['session', 'password']

      resources :posts
      resources :events
      resources :partners, only: [:index]

      resources :projects, except: [:show] do
        get :json_names, on: :collection
      end
      resources :organizations do
         get :json_names, on: :collection
      end
      resources :external_organizations do
         get :json_names, on: :collection
      end

      resources :workshops

      resources :images, only: [:destroy]
      # resources :external_partners, only: [:index]
      match 'external_partners' => "organizations#edit_external_partners"
      match 'update_external_partners' => "organizations#update_external_partners"
    end

    resources :external_partnerships, only: [:index, :show]
    resources :external_organizations, only: [:index, :show]
    resources :posts, only: [:index, :show, :update]
    resources :events, only: [:index, :show, :update]
    resources :projects, only: [:index, :show, :update]
    resources :organizations, only: [:index, :show]
    resources :workshops, only: [:index, :show]
    resources :pages, only: [:new, :update, :create, :edit]

    get '/pages/:slug', to: 'pages#show', as: 'page'

    match 'admin/edit_profile' => 'admin/organizations#edit'

    root to: 'home#index'
  end
end

app/models/organization.rb
# encoding: utf-8
class Organization < ActiveRecord::Base
  PAPERCLIP_STORAGE_OPTS = {
    styles: {
      micro: '40x40>',
      small_thumb: '60x60>',
      mini: '120x120>',
      big_thumb: '140x140>',
      medium: '220x220>'
    }
  }

  if Rails.env.production?
    PAPERCLIP_STORAGE_OPTS.merge!(
      storage: :s3,
      s3_credentials: S3_SECRETS,
      path: "/organizations/:id/:style/:filename",
      s3_host_name: 's3-eu-west-1.amazonaws.com',
      default_url: '/assets/missing_:style_organization.png'
    )
  end

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :logo, :address, :email, :name, :telephone, :url, :keywords, :definition, :description, :twitter_name, :facebook_url, :linkedin_url, :external_partner_ids, :images, :images_attributes

  # has_one   :user
  has_many  :projects
  has_many  :events
  has_many  :partners, through: :projects, uniq: true
  has_many  :partnership
  has_many  :partnering_projects, :through => :partnership, :source => :project
  has_many  :event_partnership
  has_many  :partnering_events, :through => :event_partnership, :source => :event
  has_many  :workshop_partnership
  has_many  :partnering_workshops, :through => :workshop_partnership, :source => :workshop
  has_many  :external_partnership
  has_many  :external_partners, :through => :external_partnership, :source => :external_organization
  has_many  :images, :as => :imageble, :order => 'id ASC'

  accepts_nested_attributes_for :images, allow_destroy: true

  validates_presence_of :name
  validates_length_of :definition, :minimum => 10, :maximum => 150, :allow_blank => false, :message => 'la definizione deve essere presente e meno lunga di 150 caratteri'

  acts_as_gmappable :address => "address", :normalized_address => "address",
                    :msg => "Ci spiace ma nemmeno Google riesce a capire dov'è quell'indirizzo",
                    :check_process => false,
                    :language => "it",
                    :process_geocoding => :should_geocode?

  # accepts_nested_attributes_for :user

  has_attached_file :logo, PAPERCLIP_STORAGE_OPTS

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  def all_partners
    ap = []
    ap |= self.partners
    # ora aggiungo tutte le organizzazioni dentro ai progetti di cui IO sono partner
    self.partnering_projects.each do |p|
      ap |= p.all_organizations
    end
    ap
  end

  def set_invitation_accepted
    self.invitation_accepted_at = 1.day.ago
    self.save
  end

  def should_geocode?
    !self.address.nil?
  end

  def self.visible
    where("invitation_accepted_at <?", Time.now)
  end

  def all_projects
    (self.projects | partnering_projects)
  end

  def image(style="medium")
    if images.empty?
      "/assets/missing_#{style}_project.jpg"
    else
      images[0].data(style)
    end
  end

  private

  def self.retrieve_hash(id_array)
    id_array.map do |id|
      {
        "id" => id,
        "name" => Organization.find(id).name
      }
    end
  end
end

app/controllers/admin/organizations_controller.rb
# encoding: UTF-8
class Admin::OrganizationsController < ApplicationController
  before_filter :authenticate_organization!
  before_filter :protect_admin, only: %i[index destroy new create]
  # before_filter :prevent_external_editing, :only => ["edit", "update"]

  def edit
    @organization = params[:id].nil? ? current_organization : (admin? ? Organization.find(params[:id]) : current_organization)
    @current_tab =  (params[:id].nil? || params[:id] == current_organization.id)  ? "edit_profile" : "organizations"
    @organization.images.build
  end

  def update
    @current_tab =  (params[:id].nil? || params[:id] == current_organization.id)  ? "edit_profile" : "organizations"

    params[:organization].delete(:password) if params[:organization][:password].blank?
    params[:organization].delete(:password_confirmation) if params[:organization][:password_confirmation].blank?
    @organization = admin? ? Organization.find(params[:id]) : current_organization

    if @organization.update_attributes(params[:organization])
      sign_in @organization, :bypass => true unless (admin? && @organization.id != current_organization.id)
      redirect_to edit_admin_organization_path(@organization)
    else
      render "edit"
    end
  end

  def edit_external_partners
    @organization = current_organization
    @hash_external_partners = ExternalOrganization.retrieve_hash(@organization.external_partners.collect{|eo| eo.id})
  end

  def update_external_partners
    @organization = current_organization
    if @organization.update_attributes(params[:organization])
      redirect_to admin_external_partners_path
    else
      render "edit"
    end
  end

  def index
    @organizations = Organization.invitation_accepted
  end

  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    redirect_to admin_organizations_path

  end

  def new
    @organization = Organization.new
    @organization.images.build
  end

  def create
    @organization = Organization.new
    @organization.invitation_accepted_at = Time.now

    if @organization.update_attributes(params[:organization])
      redirect_to admin_organizations_path
    else
      render "new"
    end
  end

  def json_names
    # @organizations = Organization.all(:conditions => ["UPPER(name) LIKE UPPER(?) AND id !=?", params[:q].to_s + '%', current_organization], :limit => 12)
    @organizations = Organization.all(:conditions => ["UPPER(name) LIKE UPPER(?)", params[:q].to_s + '%'], :limit => 12)
    @organizations.collect{|organization|
      {:id => organization.id, :name => organization.name}
    }

    respond_to do |format|
      format.json { render :json => @organizations }
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  before_filter :find_organization, only: [:show]

  def index
    q = params[:q].blank? ? {'s' => 'name asc'} : params[:q]
    @search = Organization.visible.search(q)
    @organizations = @search.result
  end

  def show
    @current_tab = "organizations"
    @organization = Organization.find(params[:id])
    @events = @organization.events.upcoming
    @projects = @organization.projects
    @markers = @organization.to_gmaps4rails do |event, marker|
      marker.picture(
        {
          picture: "/assets/event_marker.png",
          width: 32,
          height: 36
        }
      )
    end
    @projects_count = @projects.count
    @events_count = @organization.events.count
    @partners = @organization.partners
    @external_partners = @organization.external_partners
  end

  def find_organization
    @organization = Organization.find params[:id]
    # If an old id or a numeric id was used to find the record, then
    # the request path will not match the post_path, and we should do
    # a 301 redirect that uses the current friendly id.
    if request.path != organization_path(@organization)
      return redirect_to @organization, :status => :moved_permanently
    end
  end
end

app/helpers/admin/organizations_helper.rb
module Admin::OrganizationsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/admin/organizations/_form.html.erb
<%= semantic_form_for [:admin, @organization], html: { autocomplete: "off"} do |f| %>
  <%= f.inputs do %>

    <% unless @organization.logo.nil? %>
       <div class="square_logo">
          <%= image_tag @organization.logo(:mini) %>
       </div>
    <% end %>
    <%= f.input :logo, :label =>"Carica logo", :wrapper_html => {:class => "float half extra_hint"}, :hint => "immagine quadrata > 150x150 px" %>
    <%= f.input :name,         :label =>"Nome dell'organizzazione", :wrapper_html => {:class => "float half"} %>

    <%= f.input :email,  :wrapper_html => {:class => "clearform"}, :input_html =>{:autocomplete => "off"} %>
    <%= f.input :password,  :wrapper_html => {:class => "half float first"},  :input_html =>{:autocomplete => "off"} %>
    <%= f.input :password_confirmation,  :wrapper_html => {:class => "half float"} %>
    <%= f.input :keywords,  :wrapper_html => {:class => "clearform"}, :hint => "Separa le parole chiave da una virgola", :placeholder => "es: urban game, maternage, genitorialità" %>
    <%= f.input :definition,   :as => "text", :label =>"Definizione",    :hint => "La tua organizzazione in 150 caratteri", :input_html => { :class => 'autogrow', :rows => 2, :counter => 150 },  :wrapper_html => {:class => 'countit clearform'}  %>

    <%= f.input :description,  :label =>"Descrizione",    :hint => "I vostri obiettivi, le vostre attività, la vostra storia, ecc...", :input_html => { :class => 'autogrow', :rows => 8  }  %>
    <%= f.input :address,      :label =>"Indirizzo",      :placeholder => "es: Piazza Duca d'Aosta 15, Milano", :hint => "avete una sede? inserite qui l'indirizzo"   %>
    <%# gmaps4rails(@json_event) %>
    <%= gmaps({
        "map_options" => {"zoom" => 17, "auto_zoom" => false},
        "markers" => { "data" => @json_event }
        }) if @json_event %>
    <%= f.input :telephone,        :label =>"Telefono", :hint => "Ufficio o cellulare",     :placeholder => "es: 02 10236545", :wrapper_html => {:class => 'half float first'} %>
    <%= f.input :url,              :label =>"Sito web",     :placeholder => "es: www.focuscoop.it", :wrapper_html => {:class => 'half float'} %>
    <%= f.input :twitter_name,     :label =>"Nome Twitter", :placeholder => "es: @livellosette", :wrapper_html => {:class => 'clearform right_hint'}, :hint => "se avete un account Twitter inserite qui il vostro nome" %>
    <%= f.input :facebook_url,     :label =>"Pagina Facebook", :placeholder => "es: https://www.facebook.com/criticalcity.upload", :wrapper_html => {:class => 'right_hint'}, :hint => "indirizzo della pagina Facebook della vostra organizzazione " %>
    <%= f.input :linkedin_url,     :label =>"Pagina Linkedin", :placeholder => "es: http://www.linkedin.com/company/focus-soc-coop-sociale", :wrapper_html => {:class => 'right_hint'}, :hint => "indirizzo della pagina Linkedin della vostra organizzazione " %>

    <% unless f.object.new_record? %>
       <%= f.inputs "Images" do %>
          <%= f.semantic_fields_for :images do |image| %>
             <% unless image.object.new_record? %>
                <%= link_to (image_tag image.object.data(:mini)), admin_image_path(image.object.id), :class => "upload_image", method: :delete unless image.object.id.nil?  %>
             <% else %>
                <%# link_to (image_tag image.object.data(:mini), :class => "upload_image"), admin_image_path(image.object.id), method: :delete unless image.object.id.nil?  %>
                <%= image.input :data, :label =>"Carica una nuova immagine", :wrapper_html => {:class => "image_field"}, :name => "Add Image" %>
             <% end %>
          <% end %>
       <% end %>
    <% end %>


  <% end %>
  <%= f.action :submit, :button_html => { :value => 'Salva' } %>
<% end %>

<%= button_to "Elimina organizzazione", admin_organization_path(@organization), method: :delete, :confirm => "Sei sicuro di voler cancellare questa organizzazione?", :method => :delete unless @organization.new_record? if admin? && @organization != current_organization %>

app/views/admin/organizations/_prepopulate.html.erb
$(document).ready(function() {
  <% if @hash_partners.size > 0 %>
    <% @hash_partners.each do |jp| %>
      if ( $( "#project_partner_ids" ).length ) {
         $("#project_partner_ids").tokenInput("add", {id: <%= jp["id"] %>, name: "<%= jp["name"] %>" });
      }

      if ( $( "#event_event_partner_ids" ).length ) {
         $("#event_event_partner_ids").tokenInput("add", {id: <%= jp["id"] %>, name: "<%= jp["name"] %>" });
      }

      if ( $( "#workshop_workshop_partner_ids" ).length ) {
         $("#workshop_workshop_partner_ids").tokenInput("add", {id: <%= jp["id"] %>, name: "<%= jp["name"] %>" });
      }      

    <% end %>
  <% end %>
})

app/views/admin/organizations/edit.html.erb
<div class="grid_7">
   <h1 class="o_1">Modifica organizzazione</h1>
   
   <%= render "/admin/organizations/form" %>
   
</div>

app/views/admin/organizations/edit_external_partners.html.erb
<div class="grid_7">
   <h1 class="o_5">I nostri partner istituzionali</h1>
   

    <%= semantic_form_for([:admin, @organization]), :html => { :class => "clearfix"}, :url => {:action => "update_external_partners"} do |f| %>
    <%= f.inputs do %>
       <%= f.input :external_partner_ids,  :label =>"Partner Istituzionali", :hint => "Scrivi nella barra il nome e scegli il partner", :placeholder => "es: Fondazione Cariplo", :as => :string, :wrapper_html => {:class => 'right_hint '}  %>
    <% end %>
     <%= f.action :submit, :button_html => { :value => 'Salva' } %>
  <% end %>
  
  <%= prepopulate_external_partners %>
  
  <p class="far_bottom">Non trovi un tuo partner istituzionale?  Forse non è stato ancora inserito da nessuno.<br>
     <b><%= link_to "Clicca qui per aggiungerlo", new_admin_external_organization_path %></b>
  </p>
  
</div>

app/views/admin/organizations/index.html.erb
<div class="grid_7">
  <%= link_to new_organization_invitation_path, class: "big_add_new o_7" do %>
    <%= t('.invite') %> <div><%= t('.invite_subtite') %></div>
  <% end %>

  <%= link_to new_admin_organization_path, class: "big_add_new o_3 large" do %>
    <%= t('.create') %> <div><%= t('.create_subtite') %></div>
  <% end %>

  <p class="uppercase_divider">o modificane una esistente</p><br><br>

  <%= render "/organizations/organization" %>
</div>

app/views/admin/organizations/list_for_autocomplete.json.erb
<%= 
  @organizations.collect {|organization| 
    {:id => organization.id, :name => organization.name}
  }.to_json
%>

app/views/admin/organizations/new.html.erb
<div class="grid_7">
   <h1 class="o_1">Crea una nuova organizzazione</h1>
   
   <%= render "/admin/organizations/form" %>
   
</div>